const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

function generateCard() {
  const imageInput = document.getElementById("imageInput");
  const name = document.getElementById("nameInput").value;

  if (!imageInput.files[0]) {
    alert("Please upload an image");
    return;
  }

  const img = new Image();
  img.onload = function () {

    // Clear canvas
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw image (centered)
    const imgSize = 400;
    ctx.drawImage(img, 200, 150, imgSize, imgSize);

    // Border
    ctx.strokeStyle = "#000";
    ctx.lineWidth = 5;
    ctx.strokeRect(200, 150, imgSize, imgSize);

    // Name text
    ctx.font = "bold 42px Arial";
    ctx.fillStyle = "#000";
    ctx.textAlign = "center";
    ctx.fillText(name || "Your Name", canvas.width / 2, 650);

    // Footer text
    ctx.font = "20px Arial";
    ctx.fillStyle = "#666";
    ctx.fillText("Generated by PhotoCard", canvas.width / 2, 720);
  };

  img.src = URL.createObjectURL(imageInput.files[0]);
}

function downloadCard() {
  const link = document.createElement("a");
  link.download = "photo_card.png";
  link.href = canvas.toDataURL("image/png");
  link.click();
}
